---
- hosts: all
  become: yes

  tasks:
    - name: UPGRADE PACKAGES
      apt: upgrade=dist update_cache=yes cache_valid_time=3600

    - name: INSTALL BASE PACKAGES
      apt: 
        name:
          - sudo
          - git
          - python
          - python3
          - python-pip
          - python3-pip
          - default-jre
        state: present
        autoclean: yes

    - name: ADD JENKINS REPOSITORY KEY
      apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"
        state: present

    - name: CLEAN APT LISTS
      file:
        path: "/var/lib/apt/lists/*"
        state: absent

    - name: UPDATE APT FOLLOWING APT MERGELISTS FIX
      apt: update_cache=yes

    - name: ADD JENKINS REPOSITORY
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: INSTALL JENKINS
      apt: name=jenkins update_cache=yes cache_valid_time=3600

    - name: ALLOW SUDO GROUP TO HAVE PASSWORDLESS SUDO
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'


